### ISSUE TITLE
Infinite Theme

### ISSUE THREAD

**Issue by davebeach** [BurdaMagazinOrg/thunder-distribution#100]
Are you going to open up the infinite theme for issues and contributions.  There are a number of small things that are causing some problems. 

For example the _shame.scss hsa reference to media query @media screen \0.  None of the compilers  can support that now, and the recommendation is to change to just @media screen

Just wondering if the theme is closed or open.  It is a great well done theme, one that others would like to contribute to.

**Comment by goldquest** [comment]
Hi David,
thanks for your interest.
The Infinite Theme is actually here on github. It consists of the theme itself:
https://github.com/BurdaMagazinOrg/infinite-theme
and a helper module here:
https://github.com/BurdaMagazinOrg/infinite-module.
We opened the issue queue, so that you can also contribute via issue reporting.
